"""empty message

Revision ID: 5726c194c5b8
Revises: 8bc8618fae94
Create Date: 2024-04-27 09:42:56.271964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5726c194c5b8'
down_revision = '8bc8618fae94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stl_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('material_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'material', ['material_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stl_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('material_id')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
