"""empty message

Revision ID: 850a3a5bad8a
Revises: af3e72d7c143
Create Date: 2024-06-18 11:19:02.887198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850a3a5bad8a'
down_revision = 'af3e72d7c143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('address_line1', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('address_line2', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('address_line2')
        batch_op.drop_column('address_line1')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
